export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const INCREASE_PRODUCT_QTY = "INCREASE_PRODUCT_QTY";
export const DECREASE_PRODUCT_QTY = "DECREASE_PRODUCT_QTY";
